package de.fumix.sipgator.common.api

import kotlin.js.JsExport

@JsExport
enum class Scope(id: String, val description: String): PermissionRequirement {
  ALL("all", "Full access"),
  CONTACTS_READ("contacts:read", "Read contact information"),
  DEVICES_LOCALPREFIX_READ("devices:localprefix:read", "Read your device settings for localprefix"),
  DEVICES_SIM_READ("devices:sim:read", "Read your sim device settings"),
  DEVICES_TARIFFANNOUNCEMENT_WRITE("devices:tariffannouncement:write", "Modify your device settings for tariff announcement"),
  PHONELINES_BLOCKANONYMOUS_READ("phonelines:blockanonymous:read", "Read your block anonymous settings"),
  PHONELINES_BLOCKANONYMOUS_WRITE("phonelines:blockanonymous:write", "Change your block anonymous settings"),
  PHONELINES_DEVICES_WRITE("phonelines:devices:write", "Modify your phone line devices"),
  PHONELINES_FORWARDINGS_READ("phonelines:forwardings:read", "Read your phone line forwardings"),
  PHONELINES_READ("phonelines:read", "Read your phone line settings"),
  PHONELINES_SIPGATEIO_READ("phonelines:sipgateio:read", "Read your phone line sipgate.io settings"),
  PHONELINES_SIPGATEIO_WRITE("phonelines:sipgateio:write", "Modify your phone line sipgate.io settings"),
  PHONELINES_VOICEMAILS_GREETINGS_WRITE("phonelines:voicemails:greetings:write", "Modify your phone line voicemail greetings"),
  PHONELINES_VOICEMAILS_READ("phonelines:voicemails:read", "Read your phone line voicemails"),
  PHONELINES_WRITE("phonelines:write", "Modify our phone line settings"),
  PORTINGS_READ("portings:read", "Read your portings"),
  PUSHDEVICE_REGISTER("push_device:register", "Register device for push notifications"),
  RTCM_READ("rtcm:read", "Access active calls"),
  RTCM_WRITE("rtcm:write", "Manage active calls"),
  SESSIONS_SMS_WRITE("sessions:sms:write", "Send SMS"),
  SETTINGS_SIPGATEIO_WRITE("settings:sipgateio:write", "Modify your sipgate.io settings"),
  SMS_CALLERID_WRITE("sms:callerid:write", "Modify your short message services"),
  SMS_WRITE("sms:write", "Modify your short message services"),
  USERS_READ("users:read", "Read user information"),
  ACCOUNT_READ("account:read", "Read account information"),
  ACCOUNT_WRITE("account:write", "Modify your account"),
  ADDRESSES_READ("addresses:read", "Read address information"),
  ADDRESSES_WRITE("addresses:write", "Modify your addresses"),
  AUTHORIZATION_OAUTH_CLIENTS_READ("authorization:oauth:clients:read", "Read your oauth clients"),
  AUTHORIZATION_OAUTH_CLIENTS_WRITE("authorization:oauth:clients:write", "Modify your oauth clients"),
  BALANCE_READ("balance:read", "Read balance information"),
  CONTACTS_WRITE("contacts:write", "Write contact information"),
  DEVICES_CALLERID_READ("devices:callerid:read", "Read your device settings for callerId"),
  DEVICES_CALLERID_WRITE("devices:callerid:write", "Modify your device settings for callerId"),
  DEVICES_LOCALPREFIX_WRITE("devices:localprefix:write", "Modify your device settings for localprefix"),
  DEVICES_READ("devices:read", "Read your devices"),
  DEVICES_SIM_WRITE("devices:sim:write", "Modify your sim device settings"),
  DEVICES_SIMS_ORDERS_WRITE("devices:sims:orders:write", "Order new SIM cards"),
  DEVICES_SINGLEROWDISPLAY_READ("devices:singlerowdisplay:read", "Read your device settings for single row display"),
  DEVICES_SINGLEROWDISPLAY_WRITE("devices:singlerowdisplay:write", "Modify your device settings for single row display"),
  DEVICES_TARIFFANNOUNCEMENT_READ("devices:tariffannouncement:read", "Read your device settings for tariff announcement"),
  DEVICES_WRITE("devices:write", "Modify your devices"),
  FAXLINES_NUMBERS_READ("faxlines:numbers:read", "Read your fax line numbers"),
  FAXLINES_READ("faxlines:read", "Read your fax line settings"),
  FAXLINES_WRITE("faxlines:write", "Modify your fax line settings"),
  GROUPS_("groups:devices:write", "Modify your group devices"),
  GROUPS_FAXLINES_READ("groups:faxlines:read", "Read your group faxlines"),
  GROUPS_NUMBERS_READ("groups:numbers:read", "Read numbers routed to your groups"),
  GROUPS_READ("groups:read", "Read your groups"),
  GROUPS_USERS_READ("groups:users:read", "Read your group members"),
  GROUPS_VOICEMAILS_READ("groups:voicemails:read", "Read your group voicemails"),
  HISTORY_READ("history:read", "Read your history"),
  HISTORY_WRITE("history:write", "Modify your history"),
  NOTIFICATIONS_READ("notifications:read", "Read notifications"),
  NOTIFICATIONS_WRITE("notifications:write", "Modify notifications"),
  NUMBERS_READ("numbers:read", "Read your numbers"),
  NUMBERS_WRITE("numbers:write", "Route numbers to phone lines"),
  OPENID("openid", "Identify you uniquely through your sipgate login"),
  PHONELINES_BUSYONBUSY_READ("phonelines:busyonbusy:read", "Read your busy on busy settings"),
  PHONELINES_BUSYONBUSY_WRITE("phonelines:busyonbusy:write", "Change your busy on busy settings"),
  PHONELINES_DEVICES_READ("phonelines:devices:read", "Read your phone line devices"),
  PHONELINES_FORWARDINGS_WRITE("phonelines:forwardings:write", "Modify your phone line forwardings"),
  PHONELINES_NUMBERS_READ("phonelines:numbers:read", "Read your phone line numbers"),
  PHONELINES_PARALLELFORWARDINGS_READ("phonelines:parallelforwardings:read", "Read your parallel forwardings"),
  PHONELINES_PARALLELFORWARDINGS_WRITE("phonelines:parallelforwardings:write", "Modify your parallel forwardings"),
  PHONELINES_SIPGATEIO_LOG_READ("phonelines:sipgateio:log:read", "Read your phone line sipgate.io log"),
  PHONELINES_VOICEMAILS_GREETINGS_READ("phonelines:voicemails:greetings:read", "Read your phone line voicemail greetings"),
  PHONELINES_VOICEMAILS_WRITE("phonelines:voicemails:write", "Modify your phone line voicemails"),
  PORTINGS_WRITE("portings:write", "Modify your portings"),
  SESSIONS_CALLS_WRITE("sessions:calls:write", "Initiate phone calls"),
  SESSIONS_FAX_WRITE("sessions:fax:write", "Send Fax"),
  SESSIONS_WRITE("sessions:write", "Initiate sessions"),
  SETTINGS_READ("settings:read", "Read your settings"),
  SETTINGS_SIPGATEIO_READ("settings:sipgateio:read", "Read your sipgate.io settings"),
  SETTINGS_WRITE("settings:write", "Modify your settings"),
  SMS_CALLERID_READ("sms:callerid:read", "Read your short message services"),
  SMS_READ("sms:read", "Read your short message services"),
  USERS_DEFAULTDEVICE_WRITE("users:defaultdevice:write", "Modify your default device settings"),
  ;

  override fun satisfiedByScopes(scopes: Collection<Scope>) = scopes.contains(this)
}
